### ISSUE TITLE
Error when plugging the Ueberauth module

### ISSUE THREAD

**Issue by imranismail** [ueberauth/ueberauth#12]
```
== Compilation error on file web/controllers/auth_controller.ex ==
** (FunctionClauseError) no function clause matching in anonymous fn/2 in Ueberauth.init/1
    lib/ueberauth.ex:168: anonymous fn({:identity, [{Ueberauth.Strategy.Identity, []}]}, %{}) in Ueberauth.init/1
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:198: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:186: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:186: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Controller.Pipeline.__before_compile__/1
    web/controllers/auth_controller.ex:1: Bonsai.AuthController (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by emoragaf** [comment]
@imranismail i'm having the same error, how did you fix it?

**Comment by scrogson** [comment]
@imranismail it appears to have been the typo in this PR: https://github.com/ueberauth/ueberauth_identity/pull/4

**Comment by nelsonic** [comment]
Hi gents, I'm getting an error that looks pretty similar ...
Stack Trace:
```
== Compilation error on file web/controllers/auth_controller.ex ==
** (FunctionClauseError) no function clause matching in Keyword.merge/2
    (elixir) lib/keyword.ex:566: Keyword.merge(nil, [])
    lib/ueberauth.ex:175: Ueberauth.init/1
    (plug) lib/plug/builder.ex:193: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:181: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:181: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Controller.Pipeline.__before_compile__/1
    web/controllers/auth_controller.ex:1: Dwylbot.AuthController (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
````
Did anyone figure it out?
