### ISSUE TITLE
OAuth2.Error at GET /auth/facebook/callback {:tls_alert, 'handshake failure'}

### ISSUE THREAD

**Issue by AlanMcCann** [ueberauth/ueberauth#43]
I started running into this error in my application and resorted to seeing if the ueberauth_example app had the same issue and it does when updated to use the most recent Ueberauth (0.4) and strategy (Facebook 0.5, for example) 

When trying to authenticate with Facebook, Github, or Google, I get the handshake failure alert

Has anyone else experienced this? 

Thanks!

<img width="1250" alt="screen shot 2016-11-28 at 2 19 43 pm" src="https://cloud.githubusercontent.com/assets/124184/20682497/4bf1833a-b576-11e6-81ae-9df627b9a128.png">

```
[info] Running UeberauthExample.Endpoint with Cowboy using http://localhost:4000
28 Nov 14:18:03 - info: compiled 5 files into 2 files, copied 3 in 1216ms
[info] GET /auth/facebook
[debug] Processing by UeberauthExample.AuthController.request/2
  Parameters: %{"provider" => "facebook"}
  Pipelines: [:browser]
[info] Sent 302 in 43ms
[debug] UeberauthExample.AuthController halted in Ueberauth.call/2
[info] GET /auth/facebook/callback
[debug] Processing by UeberauthExample.AuthController.callback/2
  Parameters: %{"code" => "AQAFevYCxlVAc_SuHdFugvcnLP07V95G6xEZOE0G2fuULM9ux5RNfqBSOSZ_6DA40jA7ZR-98BuhoMAUE8WZBZvm8BbS0hZM_4qlFOx3klyRNOH_OVk15V3T1rr4SonUIY6QiGGIPBHVmupFtv7Zv1_366YVMQsdf9MYU8U2ltZBnWE4ZKbPnWAEzFIerv62pWcOglmibJ1g3MdLGSmlyR6OkmonHFm20qnSiSEMrRjBbmuWDH0EC4lpYdVgDm6TIcv5pBkOnoUqTDUqxV0O7o53VGB8usEhwBtfrimLnK8PiQwr3kXDhPRi85-hXxCzaTI", "provider" => "facebook"}
  Pipelines: [:browser]
[error] SSL: :certify: tls_connection.erl:688:Fatal error: handshake failure - malformed_handshake_data

[info] Sent 500 in 314ms
[error] #PID<0.382.0> running UeberauthExample.Endpoint terminated
Server: lvh.me:4000 (http)
Request: GET /auth/facebook/callback?code=AQAFevYCxlVAc_SuHdFugvcnLP07V95G6xEZOE0G2fuULM9ux5RNfqBSOSZ_6DA40jA7ZR-98BuhoMAUE8WZBZvm8BbS0hZM_4qlFOx3klyRNOH_OVk15V3T1rr4SonUIY6QiGGIPBHVmupFtv7Zv1_366YVMQsdf9MYU8U2ltZBnWE4ZKbPnWAEzFIerv62pWcOglmibJ1g3MdLGSmlyR6OkmonHFm20qnSiSEMrRjBbmuWDH0EC4lpYdVgDm6TIcv5pBkOnoUqTDUqxV0O7o53VGB8usEhwBtfrimLnK8PiQwr3kXDhPRi85-hXxCzaTI
** (exit) an exception was raised:
    ** (OAuth2.Error) {:tls_alert, 'handshake failure'}
        (oauth2) lib/oauth2/client.ex:171: OAuth2.Client.get_token!/4
        (ueberauth_facebook) lib/ueberauth/strategy/facebook.ex:48: Ueberauth.Strategy.Facebook.handle_callback!/1
        (ueberauth) lib/ueberauth/strategy.ex:299: Ueberauth.Strategy.run_callback/2
        (ueberauth_example) web/controllers/auth_controller.ex:1: UeberauthExample.AuthController.phoenix_controller_pipeline/2
        (ueberauth_example) lib/ueberauth_example/endpoint.ex:1: UeberauthExample.Endpoint.instrument/4
        (ueberauth_example) lib/phoenix/router.ex:261: UeberauthExample.Router.dispatch/2
        (ueberauth_example) web/router.ex:1: UeberauthExample.Router.do_call/2
        (ueberauth_example) lib/ueberauth_example/endpoint.ex:1: UeberauthExample.Endpoint.phoenix_pipeline/1
        (ueberauth_example) lib/plug/debugger.ex:123: UeberauthExample.Endpoint."call (overridable 3)"/2
        (ueberauth_example) lib/ueberauth_example/endpoint.ex:1: UeberauthExample.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

System Info:

Mac OS X 10.12.1
Elixir 1.3.2 /Erlang-OTP 19.1

```
Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
```

I backtracked to Erlang 18.3 with no luck.

**Comment by shatteredaesthetic** [comment]
I can confirm; having the same issue.

I'm on Mac OSX 10.11.6
Elixir 1.3.3 / Erlang/OTP 19.1

**Comment by doomspork** [comment]
Thanks for the report @AlanMcCann!  I'll look into this today.

**Comment by doomspork** [comment]
I believe this and #44 may be related.

**Comment by AlanMcCann** [comment]
Just a note that  problem occurs for me for Google login as well as Facebook (the only two strategies I have tested)

**Comment by scrogson** [comment]
Doesn't sound like this is a problem with Ueberauth or the OAuth2 package. From the error above it was related to the `certify` app that comes with `hackney`.

As there haven't been any additional reports, I feel this issue can be closed. Feel free to open a new issue if you are still having problems.
